In [89]:
import numpy as np
import gym
import random as rd
import statistics

#env = gym.make("CliffWalking-v0")
env = gym.make("FrozenLake-v1")#, map_name="4x4")
epsilon=0.01
gamma=0.9
alpha=0.01
#Q = np.zeros([env.observation_space.n, env.action_space.n])
print(Q)
model={}
encounteredStates=[]

#sampling size for DynaQ
nDynaQ=10
nbEpisodes=50000
for i in range(0, nbEpisodes):
    state,ok=env.reset()
    firstState=state
    endOfEpisode = False
    nbSteps=0
    
    while not endOfEpisode:
            
        if rd.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state])
        next_state, reward, endOfEpisode, info,ok = env.step(action)
        model[str([state,action])]=[reward,next_state]
        if encounteredStates.count([state,action])==0:
            encounteredStates.append([state,action])

        next_max = np.max(Q[next_state])
        new_value = (1 - alpha) * Q[state,action] + alpha * (reward + gamma * next_max)
        Q[state, action] = new_value
        
        for j in range(0,nDynaQ):
            liste_temp = rd.sample(encounteredStates,1)
            list_temp=liste_temp[0]
            state = list_temp[0]
            action = list_temp[1]
            #print(list_temp)
            [reward,Sprime]=model[str([state,action])]
            Q[state, action] = (1 - alpha) * Q[state, action] + alpha * (reward + gamma * np.max(Q[Sprime]))
            #[reward,new_state] = model[str([state, action])]
            #Q[state, action] = (1 - alpha) * Q[state, action] + alpha * (reward + gamma * np.max(Q[S_p]))
            
            
        state = next_state
        nbSteps=nbSteps+1
        


Q = Q


[[8.71658369e-002 8.61859366e-002 8.62392038e-002 8.61506539e-002]
 [5.45997713e-018 2.92040504e-002 8.31650293e-002 8.42388490e-002]
 [8.24790039e-002 7.37838551e-002 9.26904279e-002 8.08677588e-002]
 [1.05377593e-002 3.87335543e-019 4.36773128e-017 7.90803254e-002]
 [9.34917220e-002 7.87685670e-002 2.02751432e-002 6.12825383e-004]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [2.57730956e-002 1.38765604e-112 1.22405388e-001 1.76213940e-050]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.85273202e-002 3.76434929e-002 9.23860870e-002 1.20425540e-001]
 [5.03867477e-013 2.23471875e-001 5.65862621e-005 3.95160053e-012]
 [3.71008845e-001 5.15491545e-004 1.61567603e-004 3.57768328e-003]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.66121432e-001 7.74830443e-005 4.87486028e-001 2.89460086e-017]
 [2.54379192e-001 8.89781707e-001 2.56173610e-001 3.80004302e-

In [90]:
#evaluation        
#env = gym.make("CliffWalking-v0", render_mode="human")
env = gym.make("FrozenLake-v1")#, map_name="4x4",render_mode="human")
averageNumberSuccesses=0
nbEpisodes =10000
for i in range(0, nbEpisodes):
    state,ok=env.reset()

    endOfEpisode = False
    
    while not endOfEpisode:
        
        action = np.argmax(Q[state])

        next_state, reward, endOfEpisode, info, ok = env.step(action)

        state = next_state


    if reward==1:
        
        averageNumberSuccesses=averageNumberSuccesses+1
        
averageNumberSuccesses=averageNumberSuccesses/nbEpisodes

print(averageNumberSuccesses)



0.7498


In [76]:
print(Q)

[[0.10770145 0.10209301 0.1048706  0.09277066]
 [0.04613421 0.03157879 0.05142674 0.09395851]
 [0.08448306 0.08710403 0.08835741 0.09124653]
 [0.06583833 0.08214516 0.04429664 0.09195863]
 [0.13042229 0.11458935 0.10213244 0.08847768]
 [0.         0.         0.         0.        ]
 [0.07379629 0.03609854 0.03173925 0.00869814]
 [0.         0.         0.         0.        ]
 [0.12543283 0.11470645 0.14278783 0.17636296]
 [0.10619509 0.23623779 0.21342757 0.13777394]
 [0.223419   0.21472848 0.09413091 0.09034325]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.29108532 0.13328403 0.37576532 0.13858704]
 [0.45651524 0.65088175 0.36005805 0.37754582]
 [0.         0.         0.         0.        ]]


In [45]:
import gym;import random;import numpy ;import statistics
env = gym.make("CliffWalking-v0")
#env = gym.make("FrozenLake-v1")#, map_name="4x4")
epsilon=0.3
gamma=0.9
alpha=0.01
Q = numpy.zeros([env.observation_space.n, env.action_space.n])
#Q= numpy.array([[0.025, 0.025, 0.925, 0.025],[0.025, 0.025, 0.025, 0.925],[0.925, 0.025, 0.025, 0.025], [0.025, 0.025, 0.025, 0.925],[0.925, 0.025, 0.025, 0.025],[0.25,  0.25,  0.25,  0.25 ],[0.025, 0.025, 0.925, 0.025],[0.25,  0.25,  0.25,  0.25 ],[0.025, 0.025, 0.025, 0.925],[0.025, 0.925, 0.025, 0.025],[0.925, 0.025, 0.025, 0.025],[0.25,  0.25,  0.25,  0.25 ],[0.25,  0.25,  0.25,  0.25 ],[0.025, 0.025, 0.925, 0.025],[0.025, 0.925, 0.025, 0.025],[0.25,  0.25,  0.25,  0.25 ]])
Q = Q
model={}
encounteredStates=[]
#sampling size for DynaQ
nDynaQ=5
nbEpisodes=1000
for i in range(0, nbEpisodes):
    state=env.reset()[0]
    firstState=state
    endOfEpisode = False
    nbSteps = 0
    
    while not endOfEpisode:
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            action = numpy.argmax(Q[state])

        next_state, reward, endOfEpisode, info,_ = env.step(action)
        model[str([state,action])]=[reward,next_state]

        if encounteredStates.count([state,action])==0:
            encounteredStates.append([state,action])

        next_max = numpy.max(Q[next_state])
        new_value = (1 - alpha) * Q[state,action] + alpha * (reward + gamma * next_max)
        Q[state, action] = new_value

        for j in range(0,nDynaQ):
            liste_temp = random.sample(encounteredStates,1)
            list_temp=liste_temp[0]
            S = list_temp[0]
            A = list_temp[1]
            [reward,next_state1] = model[str([S,A])]
            next_max = numpy.max(Q[next_state1])
            new_value = (1 - alpha) * Q[S,A] + alpha * (reward + gamma * next_max)
            Q[S, A] = new_value
        
       
        state = next_state
        nbSteps=nbSteps+1



In [39]:
print(Q)

[[0.17244995 0.18271516 0.18472532 0.17348076]
 [0.1929317  0.18273456 0.19942157 0.17935579]
 [0.19005981 0.20729279 0.20380175 0.18803494]
 [0.20945532 0.19375673 0.20371535 0.19319123]
 [0.22017679 0.22266521 0.20531424 0.20273066]
 [0.25       0.25       0.25       0.25      ]
 [0.2303306  0.2542936  0.21434322 0.22165318]
 [0.25       0.25       0.25       0.25      ]
 [0.22884312 0.26038038 0.24020042 0.24141552]
 [0.26933226 0.35247021 0.30270212 0.24735719]
 [0.31618394 0.42162866 0.28863759 0.28634612]
 [0.25       0.25       0.25       0.25      ]
 [0.25       0.25       0.25       0.25      ]
 [0.29616081 0.50079759 0.58642143 0.31728277]
 [0.34336086 0.49527302 0.88405603 0.50806335]
 [0.25       0.25       0.25       0.25      ]]


In [52]:
#evaluation        
env = gym.make("CliffWalking-v0", render_mode="human")
#env = gym.make("FrozenLake-v1", map_name="4x4")#,render_mode="human")
averageNumberSuccesses=0
nbEpisodes = 10000
G= 0
for i in range(0, nbEpisodes):
    state,ok=env.reset()

    endOfEpisode = False
    
    while not endOfEpisode:
        
        action = numpy.argmax(Q[state])

        next_state, reward, endOfEpisode, info, ok = env.step(action)

        state = next_state
        #print(action)
        print(reward)
        G += reward
        
        
print(G)


-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-

KeyboardInterrupt: 