In [10]:
#random walk in Frozen Lake, plus detection of end of episode

import gym
import random
import numpy
import numpy as np

env = gym.make('FrozenLake-v1')#,map_name = "4x4",render_mode = "human")

epsilon=0.3
gamma=0.9
alpha=0.01

Q = numpy.zeros([env.observation_space.n, env.action_space.n])
sommes = numpy.zeros([env.observation_space.n, env.action_space.n])
compteurs = numpy.zeros([env.observation_space.n, env.action_space.n])
#politique = numpy.ones([env.observation_space.n, env.action_space.n])
#politique = politique*0.25
politique = np.array([[0.025, 0.025, 0.925, 0.025],[0.025, 0.025, 0.025, 0.925],[0.925, 0.025, 0.025, 0.025], [0.025, 0.025, 0.025, 0.925],[0.925, 0.025, 0.025, 0.025],[0.25,  0.25,  0.25,  0.25 ],[0.025, 0.025, 0.925, 0.025],[0.25,  0.25,  0.25,  0.25 ],[0.025, 0.025, 0.025, 0.925],[0.025, 0.925, 0.025, 0.025],[0.925, 0.025, 0.025, 0.025],[0.25,  0.25,  0.25,  0.25 ],[0.25,  0.25,  0.25,  0.25 ],[0.025, 0.025, 0.925, 0.025],[0.025, 0.925, 0.025, 0.025],[0.25,  0.25,  0.25,  0.25 ]])

nbEpisodes=50000

for i in range(0, nbEpisodes):
    etats=[]
    actions=[]
    recompenses=[]
    state,prb=env.reset()
    
    firstState=state
    endOfEpisode = False
    nbSteps=0

    while not endOfEpisode:
        etats.append(state)

        u=random.uniform(0,1)
        somme=0
        for action in range(0,env.action_space.n):
            somme=somme+politique[state,action]
            if u<somme:
                break

        actions.append(action)
        next_state, reward, endOfEpisode, info ,prb= env.step(action) 
        recompenses.append(reward)
        
        state = next_state
        nbSteps=nbSteps+1

    #une fois la simulation terminée on met à jour nos valeurs
    G=0
    while actions:
        etat=etats.pop()
        action=actions.pop()
        recompense=recompenses.pop()

        G=G*gamma+recompense

        if etat not in etats:
            sommes[etat,action]=sommes[etat,action]+G
            compteurs[etat,action]=compteurs[etat,action]+1
            Q[etat,action]=sommes[etat,action]/compteurs[etat,action]

            for action in range(0,4):
                politique[etat,action]=epsilon/env.action_space.n

            meilleureAction=numpy.argmax(Q[etat])
            politique[etat,meilleureAction]=1-epsilon+epsilon/env.action_space.n
print(politique)
nbEpisodes=10000


#env = gym.make('FrozenLake-v1',map_name = "4x4",render_mode = "human")

#evaluation
averageNumberSuccesses=0
for i in range(0, nbEpisodes):
    state,prb=env.reset()
    
    endOfEpisode = False
    while not endOfEpisode:
        action = numpy.argmax(Q[state])

        next_state, reward, endOfEpisode, info ,prb= env.step(action) 

        state = next_state

    if reward==1:
        averageNumberSuccesses=averageNumberSuccesses+1
averageNumberSuccesses=averageNumberSuccesses/nbEpisodes

print(averageNumberSuccesses)



#evaluation random strategy
averageNumberSuccesses=0
for i in range(0, nbEpisodes):
    state,prb=env.reset()
    
    endOfEpisode = False
    while not endOfEpisode:
        next_state, reward, endOfEpisode, info,prb = env.step(env.action_space.sample()) 

        state = next_state

    if reward==1:
        averageNumberSuccesses=averageNumberSuccesses+1
averageNumberSuccesses=averageNumberSuccesses/nbEpisodes

print(averageNumberSuccesses)



[[0.075 0.775 0.075 0.075]
 [0.075 0.075 0.075 0.775]
 [0.775 0.075 0.075 0.075]
 [0.075 0.075 0.075 0.775]
 [0.775 0.075 0.075 0.075]
 [0.25  0.25  0.25  0.25 ]
 [0.075 0.075 0.775 0.075]
 [0.25  0.25  0.25  0.25 ]
 [0.075 0.075 0.075 0.775]
 [0.075 0.775 0.075 0.075]
 [0.775 0.075 0.075 0.075]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.075 0.075 0.775 0.075]
 [0.075 0.775 0.075 0.075]
 [0.25  0.25  0.25  0.25 ]]
0.5171
0.0155
